### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by btasteel636** [HakCat-Tech/RubberNugget#10]
Hi! Thank you for the help! So seemingly 3 out of the four buttons are not functioning on my Nugget. I used a jumper cable to test all four buttons and only the bottom button would indicate a button press when jumped. The bottom button works when normally pressed as well.

**Comment by NullUsxr** [comment]
Have you tried re-soldering the non-functioning buttons? Assuming it's a hardware problem, it's either a bad connection or the buttons themselves don't work.

**Comment by btasteel636** [comment]
I haven't tried resoldering yet, because I did test the buttons for continuity and all four buttons have continuity when depressed. The issue seems to be somewhere else.

**Comment by NullUsxr** [comment]
Interesting.. Have you looked at the traces on the actual board itself? If there's solder that's bridging two contacts, you should want to remove the bridge. If one of the PCB traces is destroyed or otherwise, it'd be a problem with the board.

**Comment by btasteel636** [comment]
Ok I inspected further. Looking at the backside of the nugget. I think I may have found a problem. It appears only 1 pin on the reset side of the S2 mini board is soldered. Only the pin nearest to the reset button is soldered. Can someone confirm if this is normal? I am assuming the are ALL supposed to be soldered.

**Comment by NullUsxr** [comment]
All pins are meant to be soldered on the nugget. I think that's your problem! 😄

**Comment by btasteel636** [comment]
Well that worked! I have all my buttons! What kind of solder do you guys use? I was able to get it done but the solder I was using was a little finicky and much shinier than the solder pins already done on the nugget.

**Comment by NullUsxr** [comment]
Here is [the solder we use! ](https://www.amazon.com/dp/B07XZ9LKJJ/)

**Comment by skickar** [comment]
We use lead free solder, you can find it by searching for Sn100Ni+

Thank you for helping track down this issue! We've redoubled our quality control and found several other Nuggets that had a step skipped in their production process. We found this happened when one person making Nuggets would leave partially assembled nuggets, and the next person to make nuggets would finish them and miss a step.

We've adjusted our process to check before packaging and making testing each button and not just flashing part of our outgoing test. Thanks again! I'm going to close this issue

**Comment by skickar** [comment]
@btasteel636 just FYI, these 2 bugs qualify for our bug bounty program. We'll announce the winners in a week or two depending on when our official launch is. Thanks for contributing!

**Comment by btasteel636** [comment]
Awesome! Thats so cool! Thank you all. I'm going to check out that solder. Can't wait to keep playing around with my Nugget and continue learning. Great feeling when you finally figure out a problem.
