### ISSUE TITLE
Web interface impossible to use without USB setup

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/RubberNugget#2]
Currently, you can't use the web interface until a payload is created via USB. This adds complexity to the setup process.

To fix this, we can take one of two actions:

1. Add a create payload option to the web interface, which drops payloads into the proper space
2. Pre-fill the OS folders with payload types and dummy payloads in each one which can be edited via the web interface

**Comment by skickar** [comment]
It's also not clear what the limits to our setup are when it comes to how many folders are allowed, so setting this up by default would be the best route

**Comment by AlexLynd** [comment]
This issue has been mitigated in the latest release [here](https://github.com/HakCat-Tech/RubberNugget/releases/tag/v1.0.4-beta).  You can create payloads and assign them an operating system / category type.  The binary also includes example payloads for reference.
