### ISSUE TITLE
CTRL in script doesn't work on Linux

### ISSUE THREAD

**Issue by brandonpaiz** [HakCat-Tech/RubberNugget#35]
Ran script with unsaved document open in text editor:
```
STRING the script is running
DELAY 1000
CTRL S
```
Expected the save dialog to pop up. Output: `the script is runnings`. Note the `s`

I changed the line ending style from unix to dos just to see if that had any effect. I ran the script again and received output `the script is running`, but still no save dialog.

**Comment by brandonpaiz** [comment]
Flashed from latest release: v1.0.4 (beta)
MD5 `6e281e2028942c818fec4dd713e58a05` (I think I've seen the release updated before, so this may be more specific)


UNIX line endings
```
File size: 47 bytesFile successfully read!
STRING the script is running
String

DELAY 1000
Delayed!

CTRL S
looking for: CTRL
CTRL
 found!
5
S  83
22
looking for: 
Command not found
finished running payload

```

DOS line endings
```
File size: 50 bytesFile successfully read!
STRING the script is running

String

DELAY 1000

Delayed!

CTRL S

looking for: CTRL
CTRL
 found!
5
looking for: 
Command not found
finished running payload
```

**Comment by AlexLynd** [comment]
Huh! This might be an issue with the EspTinyUSB library - it looks like hidkeyboard.cpp isn't properly appending the `keycode` array with modifiers.  I forked the library and implemented a [fix here that seems to be working](https://github.com/HakCat-Tech/EspTinyUSB/commit/781b8cce247474eea00e49e3cbeab4b28e567921), let me know what you think!
