### ISSUE TITLE
Not possible to delete payloads from web interface

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/RubberNugget#4]
When using the web interface, it's impossible to delete payloads.

On MacOS, this means saving via USB creates hidden files which take up all the slots and can't be deleted via the web interface.

**Comment by AlexLynd** [comment]
We added this feature to the latest update!  Download [v1.0.4 here.](https://github.com/HakCat-Tech/RubberNugget/releases/tag/v1.0.4-beta)
