### ISSUE TITLE
Unclear limits on folders/payload creation

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/RubberNugget#5]
We need to make it stupid obvious that the following limitations exist, as they are not intuitive:

1. Each OS folder gets a MAX of 3 category folders
2. Each category folder gets a MAX of 3 payloads
3. Payloads MUST be placed in a payload Category folder (OS folder -> Category Folder -> Payload.txt)
4. Payloads left in the OS folder will not be shown, folders in a payload Category folder will not be shown

We need to either add documentation or guard rails to make it easier to follow these conventions.

I think we should add payload slots, and let the user customize each one from the default label to whatever they want. This creates the default file tree and blank spaces for the user to fill out, while preventing file operations outside our schema.

**Comment by brandonpaiz** [comment]
solved when https://github.com/HakCat-Tech/RubberNugget/issues/9 is
